version: "3.9"
services:
  db:
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_HOST=DB_HOST
        - POSTGRES_PORT=DB_PORT
        - POSTGRES_DB=DB_NAME
        - POSTGRES_USER=DB_USER
        - POSTGRES_PASSWORD=DB_PASS
        
  web:
    environment:
      - SECRET_KEY
      - DEBUG
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db