# Generated by Django 3.1.7 on 2021-05-19 15:40

from django.db import migrations, models
import phonenumber_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20210519_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[phonenumber_field.validators.validate_international_phonenumber]),
        ),
    ]
