# Generated by Django 3.1.7 on 2021-02-27 11:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carowners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spareparts/category')),
            ],
            options={
                'verbose_name_plural': 'sparepart categories',
            },
        ),
        migrations.CreateModel(
            name='SparePartSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparedealers.sparepartcategory')),
            ],
            options={
                'verbose_name_plural': 'sparepart subcategories',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('year_of_manufacture', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid year', regex='[0-9,]')])),
                ('photo', models.ImageField(upload_to='spareparts/')),
                ('is_featured', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^07[0-9]'), django.core.validators.MinLengthValidator(limit_value=10, message='Phone number should have 10 values')])),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=100)),
                ('store', models.CharField(blank=True, max_length=100, null=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carowners.carmake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carowners.carmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_categories', to='sparedealers.sparepartcategory')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparedealers.condition')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_subcategories', to='sparedealers.sparepartsubcategory')),
            ],
        ),
    ]
