# Generated by Django 3.0.3 on 2020-03-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartsubcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='sparepartcategory',
            name='sub_category',
            field=models.ManyToManyField(to='sparedealers.SparePartSubCategory'),
        ),
    ]
