# Generated by Django 3.0 on 2020-02-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartcategory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='spareparts/category'),
        ),
    ]
