# Generated by Django 3.0.3 on 2020-03-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparedealer',
            name='sparepart',
        ),
        migrations.AddField(
            model_name='sparedealer',
            name='spareparts',
            field=models.ManyToManyField(to='sparedealers.SparePart'),
        ),
    ]
