# Generated by Django 2.2.10 on 2020-02-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0002_auto_20200219_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparedealer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='spareparts/'),
        ),
    ]
