# Generated by Django 3.0.3 on 2020-03-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0002_auto_20200306_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='sparedealer',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='first_name',
            field=models.CharField(default='Dealer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='last_name',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='location',
            field=models.CharField(default='Nairobi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='phone_number',
            field=models.CharField(default='0711223344', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='store',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_categories', to='sparedealers.SparePartCategory'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_subcategories', to='sparedealers.SparePartSubCategory'),
        ),
        migrations.DeleteModel(
            name='SpareDealer',
        ),
    ]
