# Generated by Django 3.0 on 2020-02-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0002_auto_20200209_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sparepartcategory', to='sparedealers.SparePartCategory'),
        ),
    ]
