# Generated by Django 3.0.3 on 2020-03-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0003_auto_20200306_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='location',
            new_name='place',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='region',
            field=models.CharField(default='Nairobi', max_length=20),
            preserve_default=False,
        ),
    ]
