# Generated by Django 3.0.3 on 2020-03-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0004_auto_20200306_0651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepartcategory',
            options={'verbose_name_plural': 'sparepart categories'},
        ),
        migrations.AlterModelOptions(
            name='sparepartsubcategory',
            options={'verbose_name_plural': 'sparepart subcategories'},
        ),
    ]
