# Generated by Django 3.0.3 on 2020-03-07 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0005_auto_20200306_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^07[0-9]')]),
        ),
    ]
