# Generated by Django 3.0.3 on 2020-03-07 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0006_auto_20200307_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='year_of_manufacture',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='Enter a valid year', regex='[0-9],')]),
        ),
    ]
