# Generated by Django 3.0.3 on 2020-03-12 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0008_auto_20200307_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^07[0-9]'), django.core.validators.MinLengthValidator(limit_value=10, message='Phone number should have 10 values')]),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='year_of_manufacture',
            field=models.CharField(max_length=225, validators=[django.core.validators.RegexValidator(message='Enter a valid year', regex='[0-9,]')]),
        ),
    ]
