# Generated by Django 3.0.3 on 2020-03-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0010_sparepart_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='dealer',
        ),
    ]
