# Generated by Django 3.0.3 on 2020-04-18 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0013_auto_20200314_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='year_of_manufacture',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Enter a valid year', regex='[0-9,]')]),
        ),
    ]
