# Generated by Django 3.0.3 on 2020-04-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0016_auto_20200426_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='place',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='region',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='location',
            field=models.CharField(default='kenya', max_length=100),
            preserve_default=False,
        ),
    ]
