# Generated by Django 3.0.3 on 2020-07-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparedealers', '0017_auto_20200427_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparedealers.Condition'),
        ),
    ]
