version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: sparesnmechs
          POSTGRES_DB: sparesnmechs

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -r

      - store_artifacts:
          path: test-reports
          destination: test-reports
