# Generated by Django 2.2.7 on 2019-11-23 13:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpareDealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.TextField()),
                ('spare_parts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.SparePart')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.TextField()),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.Speciality')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.Store')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.CarMake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.CarModel')),
            ],
        ),
    ]
