# Generated by Django 3.0 on 2020-02-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carowners', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('commonuserfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.CommonUserFields')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Store')),
            ],
            bases=('common.commonuserfields',),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('commonitemfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.CommonItemFields')),
                ('is_featured', models.BooleanField(default=False)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carowners.CarMake')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mechanics.Mechanic')),
            ],
            bases=('common.commonitemfields',),
        ),
    ]
