# Generated by Django 2.2.10 on 2020-02-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'specialities'},
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='mechanic',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='specialities',
            field=models.ManyToManyField(to='mechanics.Speciality'),
        ),
    ]
