# Generated by Django 3.0.3 on 2020-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_auto_20200306_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='place',
            field=models.CharField(default='hapa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='region',
            field=models.CharField(default='nai', max_length=20),
            preserve_default=False,
        ),
    ]
