# Generated by Django 3.0.3 on 2020-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0003_auto_20200306_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=14),
            preserve_default=False,
        ),
    ]
