# Generated by Django 3.0.3 on 2020-03-07 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0005_auto_20200307_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^07[0-9]')]),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mechanic/'),
        ),
    ]
