# Generated by Django 3.0.3 on 2020-03-12 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0006_auto_20200307_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^07[0-9]'), django.core.validators.MinLengthValidator(limit_value=10, message='Phone number should have 10 values')]),
        ),
    ]
