# Generated by Django 3.0.3 on 2020-03-14 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mechanics', '0008_speciality_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
