# Generated by Django 3.0.3 on 2020-04-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0009_auto_20200314_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='description',
            field=models.TextField(default='describe'),
            preserve_default=False,
        ),
    ]
