# Generated by Django 3.0.3 on 2020-05-01 19:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carowners', '0001_initial'),
        ('mechanics', '0010_auto_20200419_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={},
        ),
        migrations.RenameField(
            model_name='speciality',
            old_name='first_name',
            new_name='speciality',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='car_make',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='description',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='name',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='place',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='price',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='region',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='store',
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False)),
                ('garage', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^07[0-9]'), django.core.validators.MinLengthValidator(limit_value=10, message='Phone number should have 10 values')])),
                ('logo', models.ImageField(upload_to='mechanic/')),
                ('location', models.CharField(max_length=100)),
                ('car_make', models.ManyToManyField(to='carowners.CarMake')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('speciality', models.ManyToManyField(to='mechanics.Speciality')),
            ],
            options={
                'verbose_name_plural': 'specialities',
            },
        ),
    ]
