# Generated by Django 3.0.3 on 2020-05-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0011_auto_20200501_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'specialities'},
        ),
    ]
