# Generated by Django 3.0.3 on 2020-07-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0012_auto_20200501_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='speciality',
            field=models.ManyToManyField(related_name='specialities', to='mechanics.Speciality'),
        ),
    ]
