# Generated by Django 3.0 on 2020-02-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('commonitemfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.CommonItemFields')),
                ('photo', models.ImageField(upload_to='spareparts/car_make')),
            ],
            bases=('common.commonitemfields',),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('commonitemfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.CommonItemFields')),
                ('photo', models.ImageField(upload_to='spareparts/car_model')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carowners.CarMake')),
            ],
            bases=('common.commonitemfields',),
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('commonuserfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.CommonUserFields')),
                ('car_make', models.ManyToManyField(to='carowners.CarMake')),
                ('car_model', models.ManyToManyField(to='carowners.CarModel')),
            ],
            bases=('common.commonuserfields',),
        ),
    ]
