# Generated by Django 3.0 on 2020-02-01 11:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='spareparts/car_make')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='spareparts/car_model')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.CarMake')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='spareparts/')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='spareparts/category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spareparts.Common')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.Store')),
            ],
            bases=('spareparts.common',),
        ),
        migrations.CreateModel(
            name='SpareDealer',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spareparts.Common')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.Store')),
            ],
            bases=('spareparts.common',),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.CarMake')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.Mechanic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SparePartSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.SparePartCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LOCALLY USED', 'Locally Used'), ('FOREIGN USED', 'Foreign Used')], max_length=255)),
                ('year_of_manufacture', models.CharField(max_length=225)),
                ('photo', models.ImageField(upload_to='spareparts/')),
                ('car_make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.CarMake')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.CarModel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.SparePartCategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.SparePartSubCategory')),
                ('sparedealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.SpareDealer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False)),
                ('speciality', models.ManyToManyField(to='spareparts.Speciality')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.Mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedSparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False)),
                ('sparepart', models.ManyToManyField(to='spareparts.SparePart')),
                ('sparedealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spareparts.SpareDealer')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spareparts.Common')),
                ('car_make', models.ManyToManyField(to='spareparts.CarMake')),
                ('car_model', models.ManyToManyField(to='spareparts.CarModel')),
            ],
            bases=('spareparts.common',),
        ),
    ]
