# Generated by Django 3.1.7 on 2021-07-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepartcategory',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepartcategory',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepartsubcategory',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepartsubcategory',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
