# Generated by Django 3.1.7 on 2021-07-24 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0002_auto_20210720_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 6, 42, 441667)),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 6, 42, 441723)),
        ),
        migrations.AlterField(
            model_name='sparepartcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 6, 42, 441667)),
        ),
        migrations.AlterField(
            model_name='sparepartcategory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 6, 42, 441723)),
        ),
        migrations.AlterField(
            model_name='sparepartsubcategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 6, 42, 441667)),
        ),
        migrations.AlterField(
            model_name='sparepartsubcategory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 11, 6, 42, 441723)),
        ),
    ]
